tezos_doner/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('profile/', views.profile, name='profile'),
    path('invite_person/', views.saveprofile, name='invite_person'),
    path('search_users/', views.search_users, name='search_users'),
    path('', views.home, name='home'),
    path('send_invitation/', views.send_invitation, name='send_invitation'),
    path('book_appointment/', views.book_appointment, name='book_appointment'),
    path('appointment_success/', views.appointment_success, name='appointment_success'),
    path('load_timeslots/', views.load_timeslots, name='load_timeslots'),
    path('confirm_appointment/', views.confirm_appointment, name='confirm_appointment'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings

class CustomUser(AbstractUser):
    blockchain_contract_id = models.CharField(max_length=100, blank=True, null=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    iin_number = models.CharField(max_length=100, blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)
    weight = models.IntegerField(blank=True, null=True)
    blood_group = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f"{self.name} {self.last_name}"

class Hospital(models.Model):
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class HospitalManager(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} - {self.hospital}"

class TimeSlot(models.Model):
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    available = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.hospital.name} - {self.date} {self.start_time} - {self.end_time}"

class Appointment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    timeslot = models.ForeignKey(TimeSlot, on_delete=models.CASCADE)
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.hospital.name} - {self.timeslot.date} {self.timeslot.start_time} - {self.timeslot.end_time}"

class Invitation(models.Model):
    email = models.EmailField()
    date = models.DateField()
    time = models.TimeField()
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    blood_group = models.CharField(max_length=100)
    invited_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='invited_user')
    sent_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sent_by')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.invited_user} - {self.hospital.name} - {self.date} {self.time}"

users/forms.py
from django import forms
from .models import Hospital, TimeSlot, CustomUser

class SignUpForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'password', 'name', 'last_name', 'email', 'iin_number', 'age', 'height', 'weight', 'blood_group', 'description']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class ContactForm(forms.Form):
    name = forms.CharField(max_length=255)
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)

class HospitalDateForm(forms.Form):
    hospital = forms.ModelChoiceField(queryset=Hospital.objects.all(), empty_label="Select a hospital")
    date = forms.DateField(widget=forms.SelectDateWidget())

class BookingForm(forms.Form):
    timeslot = forms.ModelChoiceField(queryset=TimeSlot.objects.filter(available=True), empty_label="Select a time slot")

users/views.py
from django.core.mail import send_mail
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from .models import Hospital, HospitalManager, TimeSlot, Appointment
from .forms import SignUpForm, LoginForm, ContactForm, HospitalDateForm, BookingForm
from django.db.models import Q
from django.contrib.auth import logout, authenticate, login

from django.core.mail import send_mail
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout, get_user_model
from .models import Hospital, HospitalManager, TimeSlot, Appointment, CustomUser, Invitation
from .forms import SignUpForm, LoginForm, ContactForm, HospitalDateForm, BookingForm
from django.db.models import Q
from datetime import datetime, timedelta

from .tezos_func import Create_manual, Change, Create

def home(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            send_mail(
                f'Message from {name} gmail:"{email}"',
                message,
                email,
                ['erserikdaryn82@gmail.com'],  # Your email address
                fail_silently=False,
            )

            return render(request, 'users/home.html', {'form': form, 'success': True})
    else:
        form = ContactForm()

    return render(request, 'users/home.html', {'form': form})


def search_users(request):
    query = request.GET.get('query', '')
    blood_group_filter = request.GET.get('blood_group', '')

    users = get_user_model().objects.all()

    if query:
        users = users.filter(
            Q(blockchain_contract_id__icontains=query) |
            Q(name__icontains=query) |
            Q(last_name__icontains=query) |
            Q(iin_number__icontains=query) |
            Q(age__icontains=query) |
            Q(height__icontains=query) |
            Q(weight__icontains=query) |
            Q(description__icontains=query)
        )

    if blood_group_filter:
        users = users.filter(blood_group__icontains=blood_group_filter)

    results = [{'name': user.name, 'last_name': user.last_name, 'email': user.email, 'blood_group': user.blood_group} for user in users]

    return JsonResponse({'results': results})



def signup(request):
    if request.user.is_authenticated:
        return redirect('users:profile')

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            print(Create())
            print(form.cleaned_data['age'])
            print(form.cleaned_data['height'])
            print(form.cleaned_data['weight'])
            print(form.cleaned_data['blood_group'])
            print(form.cleaned_data['description'])
            contract = Create_manual()
            print('#' + contract + '#')
            text = 'age:' + str(form.cleaned_data['age']) + ' height:' + str(
                form.cleaned_data['height']) + ' weight:' + str(form.cleaned_data['weight']) + ' blood group:' + str(
                form.cleaned_data['blood_group']) + ' description:' + str(form.cleaned_data['description'])
            Change(contract, text)

            user = form.save()
            user.blockchain_contract_id = contract
            user.save()

            send_mail(
                'Welcome to Our Site',
                'Thanks for signing up!',
                'from@example.com',
                [user.email],
                fail_silently=False,
            )

            login(request, user)
            return redirect('users:profile')
    else:
        form = SignUpForm()

    return render(request, 'users/signup.html', {'form': form})


def signin(request):
    if request.method == 'POST':
        form = LoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('users:profile')
    else:
        form = LoginForm()
    return render(request, 'users/signin.html', {'form': form})


def signout(request):
    logout(request)
    return render(request, 'users/home.html')


@login_required
def profile(request):
    return render(request, 'users/profile.html')


def saveprofile(request):
    return render(request, 'users/saveprofileform.html')


@login_required
def send_invitation(request):
    email = request.GET.get('email', '')
    date = request.GET.get('date', '')
    time = request.GET.get('time', '')
    blood_group = request.GET.get('blood_group', '')

    user = request.user
    hospital_manager = HospitalManager.objects.get(user=user)
    hospital = hospital_manager.hospital

    invited_user = CustomUser.objects.filter(email=email).first()

    if invited_user:
        invitation = Invitation.objects.create(
            email=email,
            date=date,
            time=time,
            hospital=hospital,
            blood_group=blood_group,
            invited_user=invited_user,
            sent_by=user
        )

        send_mail(
            'Invitation to Hospital Visit',
            f"Dear {invited_user.name},\n\nWe are pleased to invite you to Hospital {hospital.name}, located at {hospital.address}, on {date} at {time} for a blood donation session. Your participation is crucial to help those in need.\n\nBest regards,\n{hospital.name} Team",
            'from@example.com',
            [email],
            fail_silently=False,
        )

        return JsonResponse({'message': f'Invitation sent successfully to {email} for {date} at {time}'})
    else:
        return JsonResponse({'message': 'User not found.'}, status=404)


@login_required
def book_appointment(request):
    if request.method == 'POST':
        form = HospitalDateForm(request.POST)
        if form.is_valid():
            hospital = form.cleaned_data['hospital']
            date = form.cleaned_data['date']
            generate_time_slots(hospital, date, date)  # Generate time slots for the selected date
            timeslots = TimeSlot.objects.filter(hospital=hospital, date=date, available=True)
            booking_form = BookingForm()
            booking_form.fields['timeslot'].queryset = timeslots
            return render(request, 'users/book_appointment.html',
                          {'form': form, 'booking_form': booking_form, 'timeslots': timeslots})
    else:
        form = HospitalDateForm()

    return render(request, 'users/book_appointment.html', {'form': form})


@login_required
def confirm_appointment(request):
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            timeslot = form.cleaned_data['timeslot']
            timeslot.available = False
            timeslot.save()
            appointment = Appointment.objects.create(user=request.user, timeslot=timeslot, hospital=timeslot.hospital)

            # Send confirmation email
            send_mail(
                'Appointment Confirmation',
                f"Dear {request.user.name},\n\nYour appointment at {appointment.hospital.name} located at {appointment.hospital.address} has been confirmed for {timeslot.date} from {timeslot.start_time} to {timeslot.end_time}.\n\nThank you for booking with us!\n\nBest regards,\n{appointment.hospital.name} Team",
                'from@example.com',
                [request.user.email],
                fail_silently=False,
            )

            return redirect('users:appointment_success')
    return redirect('users:book_appointment')


@login_required
def appointment_success(request):
    return render(request, 'users/appointment_success.html')


def load_timeslots(request):
    hospital_id = request.GET.get('hospital')
    date = request.GET.get('date')
    timeslots = TimeSlot.objects.filter(hospital_id=hospital_id, date=date, available=True).values('id', 'start_time',
                                                                                                   'end_time')
    return JsonResponse(list(timeslots), safe=False)


def generate_time_slots(hospital, start_date, end_date):
    current_date = start_date
    while current_date <= end_date:
        for hour in range(10, 21):
            start_time = datetime.combine(current_date, datetime.min.time()) + timedelta(hours=hour)
            end_time = start_time + timedelta(hours=1)
            TimeSlot.objects.get_or_create(
                hospital=hospital,
                date=current_date,
                start_time=start_time.time(),
                end_time=end_time.time(),
                available=True
            )
        current_date += timedelta(days=1)

users/templates/users/book_appointment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Appointment</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(145deg, #1a1a2e, #16213e);
            color: #ffffff;
            display: flex;
            flex-direction: column;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .container {
            max-width: 800px;
            padding: 20px;
            border-radius: 8px;
            background-color: #1a1a2e;
            box-shadow: 0 10px 25px rgba(0, 0, 0, 0.2);
            box-sizing: border-box;
            margin-top: 20px;
        }

        h2 {
            text-align: center;
            color: #0abab5;
            margin-bottom: 20px;
        }

        label {
            color: #ccc;
        }

        select, input, button {
            width: 100%;
            padding: 10px;
            margin-top: 10px;
            border: none;
            border-radius: 5px;
            background-color: #0a0a16;
            color: #ffffff;
        }

        button {
            background-color: #0abab5;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #089a9a;
        }
    </style>
    <script>
        function loadTimeSlots() {
            const hospitalSelect = document.getElementById('id_hospital');
            const dateInput = document.getElementById('id_date');
            const timeSlotSelect = document.getElementById('id_timeslot');

            if (hospitalSelect.value && dateInput.value) {
                fetch(`/load_timeslots?hospital=${hospitalSelect.value}&date=${dateInput.value}`)
                    .then(response => response.json())
                    .then(data => {
                        timeSlotSelect.innerHTML = '<option value="">Select a time slot</option>';
                        data.forEach(timeslot => {
                            const option = document.createElement('option');
                            option.value = timeslot.id;
                            option.text = `${timeslot.start_time} - ${timeslot.end_time}`;
                            timeSlotSelect.appendChild(option);
                        });
                    });
            }
        }

        document.addEventListener('DOMContentLoaded', function() {
            document.getElementById('id_hospital').addEventListener('change', loadTimeSlots);
            document.getElementById('id_date').addEventListener('change', loadTimeSlots);
        });
    </script>
</head>
<body>
    <div class="container">
        <h2>Book a Blood Donation Appointment</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div id="timeslot-container" style="display: none;">
                <label for="id_timeslot">Time Slot:</label>
                <select id="id_timeslot" name="timeslot"></select>
            </div>
            <button type="submit">Book Appointment</button>
        </form>
        {% if booking_form %}
        <form method="post" action="{% url 'users:confirm_appointment' %}">
            {% csrf_token %}
            {{ booking_form.as_p }}
            <button type="submit">Confirm Appointment</button>
        </form>
        {% endif %}
    </div>
</body>
</html>

users/templates/users/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background: linear-gradient(135deg, #667eea, #764ba2);
            color: #ffffff;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            margin: 0;
            margin-top: 200px;
            margin-bottom: 50px;
            padding-top: 400px;
        }
        .home-container {
            width: 100%;
            max-width: 800px;
            padding: 20px;
            border-radius: 10px;
            background: rgba(26, 26, 46, 0.9);
            box-sizing: border-box;
            text-align: center;
            margin-top: 20px;
            margin-bottom: 50px;
        }
        header {
            width: 100%;
            padding: 10px 20px;
            box-sizing: border-box;
            position: fixed;
            top: 0;
            left: 0;
            display: flex;
            justify-content: space-between;
            z-index: 10;
            background: rgba(0, 0, 0, 0.5);
        }
        .container {
            width: 100%;
            margin-top: 100px;
        }
        #first-block {
            margin-top: 100px;
            padding-top: 100px;
        }
    </style>
</head>
<body>
    <header>
        <div class="left-buttons">
            {% if user.is_authenticated %}
            <a href="{% url 'users:profile' %}" class="button">Profile</a>
            {% endif %}
        </div>
        <div class="right-button">
            {% if not user.is_authenticated %}
            <a href="{% url 'users:signup' %}" class="button">Sign Up</a>
            <a href="{% url 'users:signin' %}" class="button">Sign In</a>
            {% endif %}
        </div>
    </header>

    <div id="first-block">
        <section class="our_ability section_padding" id="first-block">
            <div class="container" id="first-block">
                <div class="row justify-content-between align-items-center">
                    <div class="col-md-6 col-lg-6">
                        <div class="our_ability_img">
                            <img src="{% static 'img/ability_img.png' %}" alt="">
                        </div>
                    </div>
                    <div class="col-md-6 col-lg-5">
                        <div class="our_ability_member_text">
                            <h2>Welcome to the Blood Donor Blockchain Platform</h2>
                            <p>Welcome to Our Future of Blood Donation. Explore how blockchain technology is revolutionizing blood donations. Our platform leverages blockchain to enhance the transparency and security of medical data management, ensuring every donor's privacy and safety. Join our community to make a difference with every donation, secured by cutting-edge technology.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <section class="feature-area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="single-feature text-center item-padding">
                        <img src="{% static 'img/feature1.png' %}" alt="">
                        <h3>advance technology</h3>
                        <p>Creeping for female light years that lesser can't evening heaven isn't bearing tree appear.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="single-feature text-center item-padding mt-4 mt-md-0">
                        <img src="{% static 'img/feature2.png' %}" alt="">
                        <h3>comfortable place</h3>
                        <p>Creeping for female light years that lesser can't evening heaven isn't bearing tree appear.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="single-feature text-center item-padding mt-4 mt-lg-0">
                        <img src="{% static 'img/feature3.png' %}" alt="">
                        <h3>quality equipment</h3>
                        <p>Creeping for female light years that lesser can't evening heaven isn't bearing tree appear.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="single-feature text-center item-padding mt-4 mt-lg-0">
                        <img src="{% static 'img/feature4.png' %}" alt="">
                        <h3>friendly staff</h3>
                        <p>Creeping for female light years that lesser can't evening heaven isn't bearing tree appear.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="top_service our_ability padding_bottom">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-md-5 col-lg-5">
                    <div class="our_ability_member_text">
                        <h2>Innovative Blockchain Integration</h2>
                        <p>At the heart of our mission is a steadfast commitment to our donors. We prioritize your health and comfort, ensuring that each donation experience is safe, seamless, and secure. With state-of-the-art facilities, we integrate blockchain technology to safeguard your personal data, while also streamlining the donation process.</p>
                        <a href="#" class="btn_2">read more</a>
                    </div>
                </div>
                <div class="col-md-6 col-lg-6">
                    <div class="our_ability_img">
                        <img src="{% static 'img/top_service.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="home-container" >
        <h2>Contact Us</h2>
        {% if success %}
            <p>Thank you for your message! We will get back to you soon.</p>
        {% else %}
            <form method="post" action="{% url 'users:home' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">Name:</label>
                    <input type="text" class="form-control" id="id_name" name="name" required>
                </div>
                <div class="form-group">
                    <label for="id_email">Email:</label>
                    <input type="email" class="form-control" id="id_email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="id_message">Message:</label>
                    <textarea class="form-control" id="id_message" name="message" rows="5" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        {% endif %}
    </div>

</body>
<footer class="footer mt-auto py-3" style="background-color: #333; color: #fff; width: 100%; padding: 100px 20px; margin-top: 50px">
    <div class="container" style="margin-top: 50px">
        <div class="row">
            <div class="col-md-6 text-left">
                <p>© 2024 Blood Donor Blockchain Platform. All rights reserved.</p>
            </div>
            <div class="col-md-6 text-right">
                <p>Email: <a href="mailto:erserikdaryn82@gmail.com" style="color: #fff;">erserikdaryn82@gmail.com</a></p>
                <p>Phone: <a href="tel:+1234567890" style="color: #fff;">+1 234 567 890</a></p>
                <p>
                    Instagram: <a href="https://www.instagram.com/yourprofile" target="_blank" style="color: #fff;">@yourprofile</a>
                </p>
                <p>
                    WhatsApp: <a href="https://wa.me/1234567890" target="_blank" style="color: #fff;">Chat with us</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Add this at the end of your body content just before the closing </body> tag -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2poTj+7P6r4MR1yEjfuoTt3MXwC/dU3I5iT9j/tz9CJ9gWxMVOm87" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-QNx5VZ8+VeZ5G6gK8f8XuvPzXYR5B6Jsu0TeFXJfOJpX9B4Ke7nStl7qq51flX9L" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgjC5Qyu0n1+Br4hKyEfRJo1ltk5R6/zVAXX5AG8CkB3fl4k0md" crossorigin="anonymous"></script>

</html>

users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Roboto', sans-serif;
            background: linear-gradient(135deg, #667eea, #764ba2);
            color: #ffffff;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 0;
            position: relative;
        }

        .profile-container {
            width: 100%;
            max-width: 450px;
            padding: 25px;
            border-radius: 10px;
            box-shadow: 0 10px 35px rgba(0, 0, 0, 0.3);
            background: rgba(26, 26, 46, 0.8);
            box-sizing: border-box;
            text-align: left;
        }

        h2 {
            color: #4fd1c5;
            margin-bottom: 25px;
        }

        p {
            margin-bottom: 12px;
            font-size: 16px;
        }

        .user-info {
            color: #e0e0e0;
            font-weight: 500;
        }

        .home-button, .logout-button, .invite-button {
            background-color: #4fd1c5;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
            text-decoration: none;
            padding: 10px 20px;
        }

        .home-button {
            position: absolute;
            top: 20px;
            right: 120px;
        }

        .logout-button {
            position: absolute;
            top: 20px;
            right: 20px;
        }

        .wallet-balance {
            display: flex;
            align-items: center;
            margin-top: 20px;
            font-size: 18px;
        }

        .wallet-balance img {
            width: 24px;
            height: 24px;
            margin-right: 10px;
        }

        .invite-button {
            margin-top: 20px;
            display: block;
            margin-left: auto;
            margin-right: auto;
            text-align: center;
        }

    </style>
</head>
<body>
    <a href="{% url 'users:home' %}" class="home-button">Home</a>
    <div class="profile-container">
        <h2>User Profile</h2>
        {% if user.is_superuser or user.hospitalmanager_set.exists %}
            <p>Hospital Name: <span class="user-info">{{ user.hospitalmanager.hospital.name }}</span></p>
            <p>Hospital Address: <span class="user-info">{{ user.hospitalmanager.hospital.address }}</span></p>
            <p>Username: <span class="user-info">{{ user.username }}</span></p>
            <a href="{% url 'users:invite_person' %}" class="invite-button">Invite Person</a>
        {% else %}
            <p>First Name: <span class="user-info">{{ user.name }}</span></p>
            <p>Last Name: <span class="user-info">{{ user.last_name }}</span></p>
            <p>Email: <span class="user-info">{{ user.email }}</span></p>
            <p>IIN Number: <span class="user-info">{{ user.iin_number }}</span></p>
            <p>Age: <span class="user-info">{{ user.age }}</span></p>
            <p>Height: <span class="user-info">{{ user.height }} cm</span></p>
            <p>Weight: <span class="user-info">{{ user.weight }} kg</span></p>
            <p>Blood Group: <span class="user-info">{{ user.blood_group }}</span></p>
            <p>Description: <span class="user-info">{{ user.description }}</span></p>
            <p>Blockchain <a href="https://better-call.dev/mainnet/{{user.blockchain_contract_id}}" style="color: #4fd1c5;">GO</a></p>
            <!-- Wallet Balance Section -->
            <div class="wallet-balance">
                <img src="https://cryptologos.cc/logos/tezos-xtz-logo.png" alt="Tezos Logo">
                <span>Balance: <span class="user-info">{{ user.wallet_balance }} XTZ</span></span>
            </div>
        {% endif %}
    </div>
    <!-- Logout button -->
    <a href="{% url 'users:signout' %}" class="logout-button">Log Out</a>
</body>
</html>